function paras = initParas()
% build up empty struct to store parameters
paras = struct('sessNum',[],...
               'preprocessing_info',struct,...
               'ori_Ch_var',struct,...
               'ori_ICA_result',struct,...
               'ASR_result',struct,...
               'etc',struct);
paras.preprocessing_info = struct('ori_samplingRate',[],...
                                  'resamplingRate',[],...
                                  'bandPassFilt',[],...
                                  'removedChannel',{{}});
paras.ori_Ch_var = struct('ori_var_wholeSec',[],...
                          'ori_var_cleanSec',[]);
ori_ICA = struct('icaweights',[],...
                 'icasphere',[],...
                 'ICact_ori',[],...
                 'ICact_ori_clean',[]);
paras.ori_ICA_result = struct('whole_Section',ori_ICA,...
                              'clean_Section',ori_ICA);
asr = struct('dataModified',[],...
             'var',[],...
             'ICact_ori',[],...
             'ICact_ori_clean',[],...
             'ICact_asr',[]);
paras.ASR_result = struct('cutoff',[],...
                          'icaweights',[],...
                          'icasphere',[],...
                          'whole_Section',asr,...
                          'clean_Section',asr);
paras.etc = struct('ASR_threshold',[],...
                   'clean_windows_info',struct('mask',[],'clean_portion',[]),...
                   'chanlocs',struct);
end